services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/muebleria_db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - muebleria-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - muebleria-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: muebleria_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - muebleria-network

volumes:
  db_data:


networks:
  muebleria-network:
    driver: bridge
